### ISSUE TITLE
Can't compile: undefined reference to `EVP_MD_CTX_create', `EVP_MD_CTX_destroy'

### ISSUE THREAD

**Issue by b1rdG** [RetroShare/RetroShare#1886]
Hi,

I can't compile getting following error message:

```
 Error: undefined reference to `EVP_MD_CTX_create'
 Error: undefined reference to `EVP_MD_CTX_destroy'
```

It seems that is a problem with OpenSSL 1.1.0, see:

https://stackoverflow.com/questions/46768071/openssl-linking-undefined-reference-evp-md-ctx-new-and-fre/46769674

> `EVP_MD_CTX_new()` in 1.1.0 has replaced `EVP_MD_CTX_create()` in 1.0.x.
`EVP_MD_CTX_free()` in 1.1.0 has replaced `EVP_MD_CTX_destroy()` in 1.0.x.

```bash
$ openssl version 
OpenSSL 1.1.1  11 Sep 2018

$ apt list --installed | grep libssl              
libssl-dev/bionic-updates,bionic-security,now 1.1.1-1ubuntu2.1~18.04.5 amd64 [installed]
libssl1.0.0/bionic-updates,bionic-security,now 1.0.2n-1ubuntu5.3 amd64 [installed]
libssl1.1/bionic-updates,bionic-security,now 1.1.1-1ubuntu2.1~18.04.5 amd64 [installed]
```

The `libssl1.0.0` library is isntalled but I don't know how to tell to the compiler to use it instead of  `libssl1.1`. Maybe something like the suggested [here](https://git.softwarelibre.mx/KBrown/gentoo-overlay/commit/f26b7dca1705ce6a554f964577aa58e68135f5fe) could help.

I'm working with a amd64 Linux mint 19.1 on the last master commit (40d9398b3).

**Comment by b1rdG** [comment]
Solved just uninstalling `libssl-dev` and installing `libssl1.0-dev`
