### ISSUE TITLE
userSuppliedTorExecutable not defined?

### ISSUE THREAD

**Issue by ScoreUnder** [RetroShare/RetroShare#2653]
Somewhere between f22671dda (good) and 3e4fed59 (bad), I began to get this compilation error when building from scratch:

```
main.cpp: In function ‘int main(int, char**)’:
main.cpp:243:52: error: ‘struct RsConfigOptions’ has no member named ‘userSuppliedTorExecutable’
  243 |             >> parameter('t',"opmode"        ,conf.userSuppliedTorExecutable,"tor"    ,"supply full tor eecutable path."       ,false);
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
main.cpp:397:18: error: ‘struct RsConfigOptions’ has no member named ‘userSuppliedTorExecutable’
  397 |         if(!conf.userSuppliedTorExecutable.empty())
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~
main.cpp:398:20: error: ‘setTorExecutablePath’ is not a member of ‘RsTor’
  398 |             RsTor::setTorExecutablePath(conf.userSuppliedTorExecutable);
      |                    ^~~~~~~~~~~~~~~~~~~~
main.cpp:398:46: error: ‘struct RsConfigOptions’ has no member named ‘userSuppliedTorExecutable’
  398 |             RsTor::setTorExecutablePath(conf.userSuppliedTorExecutable);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-inconsistent-missing-override’ may have been intended to silence earlier diagnostics
make[1]: *** [Makefile.retroshare-gui:14210: temp/linux-g++/obj/main.o] Error 1
```

This seems to have been introduced in 03a576589e701deb08957cfafd39c5e807c91ba8. It looks like the submodule hash for libretroshare was not updated.

**Comment by csoler** [comment]
It's probably due to independently merging pull requests in libretroshare and retroshare-gui. Just do a "git pull" in each of them.

**Comment by defnax** [comment]
@csoler close
