### ISSUE TITLE
Not compiling on Linux Mint "ERR_CERT_CRYPTO_IS_TOO_WEAK is not a member of RsInit"

### ISSUE THREAD

**Issue by RandomDude560** [RetroShare/RetroShare#2688]
I get this error while trying to compile on Linux Mint 20.2.
v0.6.6-663-g04d10d7fd
```
...
rshare.cpp: In static member function ??static bool Rshare::loadCertificate(const RsPeerId&, bool)??:
rshare.cpp:969:18: error: ??ERR_CERT_CRYPTO_IS_TOO_WEAK?? is not a member of ??RsInit??
  969 |     case RsInit::ERR_CERT_CRYPTO_IS_TOO_WEAK: QMessageBox::critical( nullptr,
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ??-Wno-inconsistent-missing-override??
...
```

**Comment by csoler** [comment]
you need to update the libretroshare submodule.

**Comment by RandomDude560** [comment]
thanks, that totally worked
