### ISSUE TITLE
Building fails with msys2 on Windows

### ISSUE THREAD

**Issue by hunbernd** [RetroShare/RetroShare#1345]
Building on Windows fails with msys2 since https://github.com/RetroShare/RetroShare/pull/1323

Also there is something wrong with the appveyor badge, build fails with the same error, but the badge is still green.

```
./temp/obj/GxsGroupDialog.o: in function `void FriendSelectionWidget::setSelectedIds<t_RsGenericIdType<16u, false, 6u>, (FriendSelectionWidget::IdType)4>(std::set<t_RsGenericIdType<16u, false, 6u>, std::less<t_RsGenericIdType<16u, false, 6u> >, std::allocator<t_RsGenericIdType<16u, false, 6u> > > const&, bool)':
/src/retroshare-gui/src/gui/common/FriendSelectionWidget.h:98: multiple definition of 
`void FriendSelectionWidget::setSelectedIds<t_RsGenericIdType<16u, false, 6u>, (FriendSelectionWidget::IdType)4>(std::set<t_RsGenericIdType<16u, false, 6u>, std::less<t_RsGenericIdType<16u, false, 6u> >, std::allocator<t_RsGenericIdType<16u, false, 6u> > > const&, bool)'; 
./temp/obj/FriendSelectionWidget.o:/src/retroshare-gui/src/gui/common/FriendSelectionWidget.cpp:693: first defined here
```

**Comment by zapek** [comment]
https://github.com/RetroShare/RetroShare/pull/1348

**Comment by hunbernd** [comment]
Fixed by zapek
