### ISSUE TITLE
Does not compile with openssl 1.1.0c

### ISSUE THREAD

**Issue by whocares0101** [RetroShare/RetroShare#590]
After updating my debian/unstable retroshare won't compile anymore.
Latest git/master (a005fa0) and up-to-date debian sid amd64.

```
# make clean
# qmake "CONFIG-=debug" "CONFIG+=release"
# make
```
```
openpgpsdk/openssl_crypto.c: In function ‘test_secret_key’:
openpgpsdk/openssl_crypto.c:48:9: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
test->n=BN_dup(skey->public_key.key.rsa.n);
^~
openpgpsdk/openssl_crypto.c: In function ‘ops_dsa_verify’:
openpgpsdk/openssl_crypto.c:395:9: error: dereferencing pointer to incomplete type ‘DSA_SIG {aka struct DSA_SIG_st}’
osig->r=sig->r;
^~
openpgpsdk/openssl_crypto.c:411:9: error: dereferencing pointer to incomplete type ‘DSA {aka struct dsa_st}’
odsa->p=dsa->p;
^~
Makefile.openpgpsdk:478: recipe for target 'temp/linux/obj/openssl_crypto.o' failed
```

**Comment by whocares0101** [comment]
I did some digging and it seems this is because debian/sid has a newer openssl version (1.1.0c-2)
https://packages.debian.org/sid/libssl1.1

The openssl changelog says
```
  *) Made RSA and RSA_METHOD opaque. The structures for managing RSA
     objects have been moved out of the public header files. New
     functions for managing these have been added.
     [Richard Levitte]

  *) Made DSA and DSA_METHOD opaque. The structures for managing DSA objects
     have been moved out of the public header files. New functions for managing
     these have been added.
     [Matt Caswell]
```

curl had a similar problem
https://github.com/curl/curl/issues/763
and they fixed it
https://github.com/curl/curl/commit/cfe16c22d7891a1f65ea8cd4c5352504a2afbddc

**Comment by csoler** [comment]
@whocares0101: you're welcome to submit a patch or a pull request if you have time. Thx for the accurate/useful information already!

**Comment by whocares0101** [comment]
After playing around for a while it gets further but does still not compile.

I made some changes to these files, do note that I'm not very experienced with C++.
openpgpsdk/src/openpgpsdk/openssl_crypto.c
https://paste.ubuntu.com/23597155/
openpgpsdk/src/openpgpsdk/signature.c
https://paste.ubuntu.com/23597157/
These two should be fine now this was only passing the right arguments around.

libretroshare/src/tcponudp/bss_tou.c
https://paste.ubuntu.com/23597161/
These changes may be partly wrong but the compiler errors are mostly gone.
I'm not sure what the BIO->ptr and BIO->num are and I didn't see any BIO_set_num there is BIO_set_data however.


This is what I get now [gcc version 6.2.1 20161124 (Debian 6.2.1-5)]
```
tcponudp/bss_tou.c:99:19: error: variable ‘BIO_METHOD methods_tou_sockp’ has initializer but incomplete type
 static BIO_METHOD methods_tou_sockp=
                   ^~~~~~~~~~~~~~~~~
```


The API changes
https://wiki.openssl.org/index.php/1.1_API_Changes

**Comment by heini** [comment]
Ran into the same problem while compiling for Stretch. Will see if I can help (my C++ skills are VERY limited, though).

**Comment by whocares0101** [comment]
Apparently there are also new methods for BIO_METHOD
https://www.openssl.org/docs/man1.1.0/crypto/BIO_meth_new.html

I put BIO_meth_new in BIO_s_tou_socket but we also need to free this later with BIO_meth_free, where would be a good place for this?
Or maybe just do it once globally and reuse the BIO_METHOD?
https://paste.ubuntu.com/23606770/

And the fun continues
```
crypto/chacha20.cpp: In function ‘bool librs::crypto::AEAD_chacha20_sha256(uint8_t*, uint8_t*, uint8_t*, uint32_t, uint8_t*, uint32_t, uint8_t*, bool)’:
crypto/chacha20.cpp:540:17: error: aggregate ‘HMAC_CTX hmac_ctx’ has incomplete type and cannot be defined
        HMAC_CTX hmac_ctx ;
                 ^~~~~~~~
crypto/chacha20.cpp:541:31: error: ‘HMAC_CTX_init’ was not declared in this scope
        HMAC_CTX_init(&hmac_ctx) ;
                               ^
crypto/chacha20.cpp:543:8: warning: ‘int HMAC_Init(HMAC_CTX*, const void*, int, const EVP_MD*)’ is deprecated [-Wdeprecated-declarations]
        HMAC_Init(&hmac_ctx,key,32,EVP_sha256()) ;
        ^~~~~~~~~
In file included from /usr/include/openssl/hmac.h:13:0,
                 from crypto/chacha20.cpp:33:
/usr/include/openssl/hmac.h:28:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur int HMAC_Init(HMAC_CTX *ctx, const void *key, int len,
 ^
crypto/chacha20.cpp:559:17: error: aggregate ‘HMAC_CTX hmac_ctx’ has incomplete type and cannot be defined
        HMAC_CTX hmac_ctx ;
                 ^~~~~~~~
crypto/chacha20.cpp:560:31: error: ‘HMAC_CTX_init’ was not declared in this scope
        HMAC_CTX_init(&hmac_ctx) ;
                               ^
crypto/chacha20.cpp:562:8: warning: ‘int HMAC_Init(HMAC_CTX*, const void*, int, const EVP_MD*)’ is deprecated [-Wdeprecated-declarations]
        HMAC_Init(&hmac_ctx,key,32,EVP_sha256()) ;
        ^~~~~~~~~
In file included from /usr/include/openssl/hmac.h:13:0,
                 from crypto/chacha20.cpp:33:
/usr/include/openssl/hmac.h:28:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur int HMAC_Init(HMAC_CTX *ctx, const void *key, int len,
 ^
Makefile.libretroshare:1733: recipe for target 'temp/linux-g++-64/obj/chacha20.o' failed

```

**Comment by heini** [comment]
@whocares0101, by providing complete files, it's hard to see what was changed. They also can't be downloaded without a logging in. Would you mind providing your changes as patch, or at least as a Gist here on Github?

**Comment by electron128** [comment]
fixed in #689
